# ownCloud with MariaDB/MySQL
#
# Access via "http://localhost:8080" (or "http://$(docker-machine ip):8080" if using docker-machine)
#
# During initial ownCloud setup, select "Storage & database" --> "Configure the database" --> "MySQL/MariaDB"
# Database user: root
# Database password: example
# Database name: pick any name
# Database host: replace "localhost" with "mysql"


#-v /<mydatalocation>/apps:/var/www/html/apps installed / modified apps
#-v /<mydatalocation>/config:/var/www/html/config local configuration
#-v /<mydatalocation>/data:/var/www/html/data the actual data of your ownCloud


version: '3.1'

services:

  owncloud:
    image: owncloud
    restart: always
    ports:
      - 8088:80
    volumes:
      - ./data/apps:/var/www/html/apps
      - ./data/config:/var/www/html/config 
      - ./data/data:/var/www/html/data
      

  mysql:
    image: mariadb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example
    volumes:
      - ./data/sql/:/var/lib/mysql
